### ISSUE TITLE
doc.go code example missing )

### ISSUE THREAD

**Issue by oktayaa** [ThalesGroup/requester#4]
I think requester.Receive is missing the closing ")".

type Resource struct {
		Color string `json:"color"`
	}
	var res Resource
	resp, body, err := requester.Receive(&res,
		requester.Get("http://api.com/resources/1",
	)
	fmt.Println(body)      // {"color":"red"}
	fmt.Println(res.Color) // red

**Comment by ansel1** [comment]
Thanks, fixed.
