### ISSUE TITLE
Discrepancy between go.mod and the actual repo path

### ISSUE THREAD

**Issue by kpumuk** [ThalesGroup/requester#6]
In the `go.mod`, the module name is declared as

```
module github.com/gemalto/requester
```

While the actual path is https://github.com/ThalesGroup/requester. This leads to an error in go mod:

```
go: downloading github.com/ThalesGroup/requester v1.1.0
go: downloading github.com/gemalto/requester v1.1.0
go get: github.com/ThalesGroup/requester@v1.0.2 updating to
	github.com/ThalesGroup/requester@v1.1.0: parsing go.mod:
	module declares its path as: github.com/gemalto/requester
	        but was required as: github.com/ThalesGroup/requester
```

**Comment by ansel1** [comment]
Let me know if that works for you, and I'll add an Installation section to the Read Me explaining it.

**Comment by kpumuk** [comment]
Thanks. This makes sense, although confusing. `gemalto` is not even mentioned in the readme :-) 

`github.com/ThalesGroup/requester` used to work in previous versions of go, but stopped in 1.16, and so was somewhat confusing as to which repo I should use. Also, `replace` in `go.mod` does not really work in this case either:

```
go: github.com/gemalto/requester@v1.1.0 used for two different module paths (github.com/ThalesGroup/requester and github.com/gemalto/requester)
```
